-- longplayr — an index for the column two pages sort on
--
-- **`albums` carried seven indexes and none on `created_at`** — title trigram,
-- `first_release_date`, `artwork_status`, `search_vector`, `hydration_status`,
-- `popularity_score`, `slug`. Checked against the migrations, not assumed.
--
-- **Two surfaces sort on it.** `getRecentAlbums` orders by `created_at desc`
-- with no filter at all, which is Home and Browse; and `catalogueOrderFor`
-- ends every catalogue sort at `created_at` so the ordering is total, making it
-- the final key on `/albums/all` under every sort and the leading key under
-- *Recently added*.
--
-- **This claims no measured improvement, and the restraint is deliberate.**
-- `product-feedback.md` F-050 records that at roughly 1,050 albums the scan
-- costs nothing measurable, and that the honest trigger to act is the catalogue
-- doubling or these pages appearing in a latency measurement — **neither is
-- observed.** What justifies the index is that the read sorts an unindexed
-- column on the two busiest pages, it is one statement, and F-050 names it as
-- separable and still useful after the rewrite it eventually wants.
--
-- **F-050 itself is not built here**, on its own trigger rather than on taste.
-- `architecture.md` §16.11.
--
-- `desc` matches the only direction either caller uses. Postgres can scan a
-- btree backwards, so the direction is a readability choice rather than a
-- functional one — stated so nobody later "fixes" it to ascending believing it
-- matters.

create index albums_created_at_idx on public.albums (created_at desc);
